name       : flare-engine
version    : '1.14'
release    : 16
source     :
    - https://github.com/flareteam/flare-game/releases/download/v1.14/flare-engine-v1.14.tar.gz : 523935a75e41de99590d9af75a56b679a43225fb69aa1d66b05a23fe0489a5d1
license    : GPL-3.0-or-later
component  : games
summary    : Free/Libre Action Roleplaying Engine (engine only)
description: |
    Flare (Free Libre Action Roleplaying Engine) is a simple game engine built to handle a very
    specific kind of game: single-player 2D action RPGs. Flare is not a reimplementation of an
    existing game or engine. It is a tribute to and exploration of the action RPG genre.
    Rather than building a very abstract, robust game engine, the goal of this project is to build
    several real games and harvest an engine from the common, reusable code.
    Flare uses simple file formats (INI style config files) for most of the game data, allowing
    anyone to easily modify game contents. Open formats are preferred (png, ogg). The game code is
    C++.
builddeps  :
    - pkgconfig(freetype2)
    - pkgconfig(SDL2_image)
    - pkgconfig(SDL2_mixer)
    - pkgconfig(SDL2_ttf)
setup      : |
    %cmake_ninja -DBINDIR="bin" -DDATADIR="share/flare"
build      : |
    %ninja_build
install    : |
    %ninja_install
